### ISSUE TITLE
Difference in XML Request (WSDL vs Non-WSDL)

### ISSUE THREAD

**Issue by uchagani** [savonrb/savon#748]
I am testing out savon's WSDL-less feature and I came across an issue.  When a custom namespace identifier is required, the request doesn't get fully built with that namespace identifier, only the top-level tags do.  See details below:

I have the following globals set for savon in a config file:

``` yaml
endpoint: http://www.webservicex.net/whois.asmx
namespace: http://www.webservicex.net
convert_request_keys_to: :camelcase
namespace_identifier: :tns
log: true
```

The XML request that gets built is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.webservicex.net" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <env:Body>
      <tns:GetWhoIs>
         <HostName>manheim.com</HostName>
      </tns:GetWhoIs>
   </env:Body>
</env:Envelope>
```

The `<HostName>` tag is missing the `tns` namespace.  When I run the same request with the WSDL provided by the service, the proper XML gets built:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://www.webservicex.net" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <env:Body>
      <tns:GetWhoIS>
         <tns:HostName>manheim.com</tns:HostName>
      </tns:GetWhoIS>
   </env:Body>
</env:Envelope>
```

WSDL for debugging purposes: [WhoIs](http://www.webservicex.net/whois.asmx?WSDL)
